version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings
        columns:
          - name: price
            tests:
              - dbt_expectations.expect_column_values_to_match_regex:
                  regex: "^\\\\$[0-9][0-9\\\\.]+$"  #dollar sign need two slash in yaml
      - name: hosts
        identifier: raw_hosts
      - name: reviews
        identifier: raw_reviews
        loaded_at_field: date
        freshness: # make this a little more strict
          warn_after: {count: 1, period: hour}
          #error_after: {count: 24, period: hour} #if latest data exceed 24 hour will occur error
        

    